from enum import Enum


class SignalType(str, Enum):
    RANGE_BREAKOUT      = "RANGE_BREAKOUT"
    RANGE_BREAKDOWN     = "RANGE_BREAKDOWN"
    CAM_H3_REVERSAL     = "CAM_H3_REVERSAL"
    CAM_H4_BREAKOUT     = "CAM_H4_BREAKOUT"
    CAM_H4_REVERSAL     = "CAM_H4_REVERSAL"
    CAM_L3_REVERSAL     = "CAM_L3_REVERSAL"
    CAM_L4_BREAKDOWN    = "CAM_L4_BREAKDOWN"
    CAM_L4_REVERSAL     = "CAM_L4_REVERSAL"
