from dataclasses import dataclass, field
from datetime import date, datetime
from decimal import Decimal
from enum import Enum
from uuid import UUID, uuid4

from trader_cockpit.domain.shared.symbol import Symbol
from .score import ScoreFactors, SignalGrade


class SignalDirection(str, Enum):
    LONG  = "LONG"
    SHORT = "SHORT"


class SignalType(str, Enum):
    EOD_SCAN   = "EOD_SCAN"    # Generated by nightly scan
    INTRADAY   = "INTRADAY"    # Generated live during market hours
    MANUAL     = "MANUAL"      # Manually added by trader


@dataclass
class Signal:
    """
    A scored trading opportunity for one instrument.
    Immutable once scored — create a new Signal if re-scored.
    """
    id: UUID
    symbol: Symbol
    security_id: str
    signal_type: SignalType
    direction: SignalDirection
    score_factors: ScoreFactors

    # Price levels
    entry_zone_low: Decimal
    entry_zone_high: Decimal
    sl_price: Decimal            # Intraday SL (tight)
    swing_sl_price: Decimal      # Swing/CNC SL (wide)
    target_price: Decimal

    # Computed at scoring time
    atr14: Decimal               # ATR(14) at time of signal
    is_eod: bool = True          # EOD scan vs intraday signal

    notes: str = ""
    generated_at: datetime = field(default_factory=datetime.utcnow)
    scan_date: date = field(default_factory=date.today)
    stale: bool = False          # Marked stale if gap > 2% or support broken

    @classmethod
    def create(
        cls,
        symbol: Symbol,
        security_id: str,
        signal_type: SignalType,
        direction: SignalDirection,
        score_factors: ScoreFactors,
        entry_zone_low: Decimal,
        entry_zone_high: Decimal,
        sl_price: Decimal,
        swing_sl_price: Decimal,
        target_price: Decimal,
        atr14: Decimal,
        is_eod: bool = True,
        notes: str = "",
    ) -> "Signal":
        return cls(
            id=uuid4(),
            symbol=symbol,
            security_id=security_id,
            signal_type=signal_type,
            direction=direction,
            score_factors=score_factors,
            entry_zone_low=entry_zone_low,
            entry_zone_high=entry_zone_high,
            sl_price=sl_price,
            swing_sl_price=swing_sl_price,
            target_price=target_price,
            atr14=atr14,
            is_eod=is_eod,
            notes=notes,
        )

    @property
    def grade(self) -> SignalGrade:
        return self.score_factors.grade(is_eod=self.is_eod)

    @property
    def total_score(self) -> int:
        return self.score_factors.weighted_total(is_eod=self.is_eod)

    @property
    def risk_reward(self) -> Decimal:
        sl_dist = abs(self.entry_zone_high - self.sl_price)
        target_dist = abs(self.target_price - self.entry_zone_low)
        if sl_dist == 0:
            return Decimal("0")
        return target_dist / sl_dist

    @property
    def intraday_sl_distance(self) -> Decimal:
        return abs(self.entry_zone_high - self.sl_price)

    @property
    def swing_sl_distance(self) -> Decimal:
        return abs(self.entry_zone_high - self.swing_sl_price)

    def mark_stale(self) -> None:
        self.stale = True


@dataclass
class WatchlistEntry:
    """One instrument on today's watchlist, derived from a Signal."""
    signal: Signal
    added_at: datetime = field(default_factory=datetime.utcnow)
    hold_days: int = 0       # For CNC positions
    is_active: bool = True

    @property
    def symbol(self) -> Symbol:
        return self.signal.symbol

    @property
    def grade(self) -> SignalGrade:
        return self.signal.grade

    @property
    def direction(self) -> SignalDirection:
        return self.signal.direction


@dataclass
class Watchlist:
    """Today's curated watchlist. Rebuilt nightly by EOD scan."""
    id: UUID
    scan_date: date
    entries: list[WatchlistEntry] = field(default_factory=list)
    generated_at: datetime = field(default_factory=datetime.utcnow)
    scan_duration_seconds: float = 0.0

    @classmethod
    def create_for_date(cls, scan_date: date) -> "Watchlist":
        return cls(id=uuid4(), scan_date=scan_date)

    def add_entry(self, entry: WatchlistEntry) -> None:
        self.entries.append(entry)

    def get_entry(self, symbol: Symbol) -> WatchlistEntry | None:
        return next((e for e in self.entries if e.symbol == symbol), None)

    def active_entries(self) -> list[WatchlistEntry]:
        return [e for e in self.entries if e.is_active and not e.signal.stale]

    def by_grade(self, grade: SignalGrade) -> list[WatchlistEntry]:
        return [e for e in self.active_entries() if e.grade == grade]
